name: model-training
on:
  - push
  - workflow_dispatch
jobs:
  run:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      - run: sudo apt-get install npm -y
      - uses: iterative/setup-cml@v1
      - name: Train model
        env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          pip install torch==1.8.0
          pip install torchvision==0.9.0
          python train.py > output.md

          cml-send-comment output.md
