name: model-training
on:
  - push
  - workflow_dispatch
jobs:
  run:
    runs-on: self-hosted
    container: docker://iterativeai/cml:0-dvc2-base1-gpu
    steps:
      - uses: actions/checkout@v2
      - name: Train model
        env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          pip install -r requirements.txt
          python train.py > output.md

          cml-send-comment output.md
