name: model-training
on:
  - push
  - workflow_dispatch
jobs:
  run:
    env:
      AGENT_TOOLSDIRECTORY: '~'
      ACTIONS_STEP_DEBUG: true
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - run: |
          sudo apt-get install npm -y
      - uses: iterative/setup-cml@v1
      - name: Train model
        env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          pip3 install -r requirements.txt
          python train.py > output.md

          cml-send-comment output.md
