name: model-training
on:
  - push
  - workflow_dispatch
jobs:
  run:
    runs-on: self-hosted
    steps:
      - name: Initial settings
        env:
          AGENT_TOOLSDIRECTORY: /opt/hostedtoolcache
        run: |
          sudo mkdir /opt/hostedtoolcache
          sudo chown azureuser /opt/hostedtoolcache
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - run: |
          sudo apt-get install npm -y
      - uses: iterative/setup-cml@v1
      - name: Train model
        env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          pip3 install -r requirements.txt
          python train.py > output.md

          cml-send-comment output.md
