name: model-training
on:
  push:
    branches:
      - '*'
      - '!master'
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - uses: iterative/setup-cml@v1
      - name: Train model
        env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          pip3 install -r requirements.txt
          mkdir outputs
          python pca.py >> stdout.md

          echo "## sruvival time histogram  " >> survival_time_hist.md
          cml-publish outputs/survival_time_hist.png --md >> survival_time_hist.md
          cml-send-comment survival_time_hist.md

          cml-send-comment outputs/group_label_count.md

          cml-send-comment stdout.md

          echo "## PCA  " >> pca.md
          cml-publish outputs/pca.png --md >> pca.md
          cml-send-comment pca.md
