name: model-training
on:
  push:
    branches:
      - '*'
      - '!master'
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - uses: iterative/setup-cml@v1
      - name: Train model
        env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          pip3 install -r requirements.txt
          python pca.py

          cml-publish output.png --md >> output.md

          cml-send-comment output.md
