name: model-training
on:
  push:
    branches:
      - '*'
      - '!master'
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      - run: |
          curl -sL https://deb.nodesource.com/setup_14.x | sudo -E bash -
          sudo apt-get install -y nodejs
          sudo apt install aptitude -y
          sudo aptitude install npm -y
      - uses: iterative/setup-cml@v1
      - name: Setup required packages via pip
        run: |
          pip3 install -r requirements.txt
      - name: Train model
        run: |
          python train.py
      - name: Publish train results
        env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          cat output.txt >> train.md
          cml-send-comment train.md
      - name: Test model
        run: |
          python test.py
      - name: Publish test results
        env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          cat output.txt >> test.md
          cml-send-comment test.md
