name: model-training
on:
  push:
    branches:
      - '*'
      - '!master'
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      - run: |
          curl -sL https://deb.nodesource.com/setup_14.x | sudo -E bash -
          sudo apt-get install -y nodejs
          sudo apt install aptitude -y
          sudo aptitude install npm -y
      - uses: iterative/setup-cml@v1
      - name: Train model
        env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          pip3 install -r requirements.txt
          python train.py >> output.md
          cml-publish output_train_fold_0.png --md >> output.md
          cml-publish output_train_fold_1.png --md >> output.md
          cml-publish output_train_fold_2.png --md >> output.md
          cml-publish output_train_fold_3.png --md >> output.md
          cml-publish output_train_fold_4.png --md >> output.md
          cat output.txt >> output.md
          cml-publish output_train_whole.png --md >> output.md

#          echo "## Training model  " >> output.md
#          cat output.txt >> output.md

#          python test.py

#          echo "## Testing model  " >> output.md
#          cml-publish sample.png --md >> output.md
#          cat output.txt >> output.md

          cml-send-comment output.md
