name: model-training
on:
  push:
    branches:
      - '*'
      - '!master'
jobs:
  dummy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
        echo Dummy Job